Add support for Python3.10
cbrichford/async-mock pull request #8
Opened 2022-01-12 21:42 UTC by lingtong-lu

2022-01-12 22:05 UTC, thehesiod commented
there isn't really a need for this module anymore, 3.8+ has built-in async unittest support

2022-01-12 22:37 UTC, cbrichford requested changes

2022-01-12 22:37 UTC, cbrichford commented on setup.py
> +  python_requires='>=3.10',
Let's set this to 3.8 so clients can upgrade to this version without upgrading to python 3.10.

2022-01-20 06:03 UTC, cbrichford approved these changes

2022-01-20 06:03 UTC, merged